language: java
install:
  - source ~/virtualenv/python2.7/bin/activate
  - pip install click pyaml
script:
  - source ~/virtualenv/python2.7/bin/activate
  - make info clean release
deploy:
  provider: releases
  api-key:
    secure: KiFHlRETVc2CTigavSLfjOAOf55FPOOA7F2UgqYd8W7JcHRfI4R6Ze+ObLbvDxEXa7fRKY/FtVQ68h7TTPEUbjS5l5SpqY/MQZWve+Soyl+3p9Rh8Im76w1bA402ETBZ3ByDepWlElL8Sz3QswIkgl166YQbUoITIeQdvR0fRwD0eI9GjtnDtl7aHxPlDLIaEbc3hOkmPtMOVAfMpypgaG6P8ehfRL6MkOwqDFPCEWY/UuuryymQDRIvmxAMfPFmOxiZdZY7kioUp8oY3NciFSeHBetFzEvEp/Lr2lzMczq6wQWssE14G5dxHmTjWIVBlWzUWGHlvx6X9ipcKuzv5u+xDDNj5pabv6Wapad9E7YIJOuu1RRnjvayQ7RjUK9tYRNGABDAUQzgpR++Hp6CNRucrt4o6aPQkOvXCpMKL+no30Y+0TUuDld65nLPwItGJPn9pHf+v2rt18QySnmhrXfKdqG2JOU3w7ofsaT2ckog6q7I3lSn8MSy3eBvkJid/t9kmVqT3T9PHP80+njivPMoSYdtk14TorvlGS4rUPSJAv8hANYKzlXJbtVcLyb1UeBg5nL9WroerqD/cT+gZuJRrdeDM0g7nW1LKMCXVpRGITjNPgyc2altAJ8214epcRCFiJPi24ObSQF4hFqtfxDpEX7Bzf6NPfSAahmS8vw=
  file_glob: true
  file:
    - NIFI-*.jar
  skip_cleanup: true
  on:
    tags: true
